pipeline {
    agent any

    stages{
        stage('Checkout') {
            step {
                sh 'git clone https://github.com/OMAR300927/My-projects.git'
            }
        }

        stage('Test') {
            step {
                sh 'pytest my-app/test_app.py -v'
            }
        }

        stage('Build') {
            step {
                sh 'docker build -t myfirstimage ./my-app'
            }
        }

        stage('Deploy K8s cluster') {
            step {
                sh 'kubectl apply -f k8s/'
            }
        }
    }
}