pipeline {
    agent any

    stages{
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Test') {
            steps {
                bat '"C:\Users\omsa3\AppData\Roaming\Python" -m pytest my-app\\test_app.py -v'
            }
        }

        stage('Build') {
            steps {
                bat 'docker build -t myfirstimage .\\my-app'
            }
        }

        stage('Deploy K8s cluster') {
            steps {
                bat 'kubectl apply -f .\\k8s\\'
            }
        }
    }
}