pipeline {
    agent any
    stages{
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build and push the image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'omarsa999',
                                usernameVariable: 'DOCKER_USER',
                                passwordVariable: 'DOCKER_PASS')]) {
                    bat 'docker login -u %DOCKER_USER% -p %DOCKER_PASS%'
                }
                bat 'docker build -t omarsa999/mysecondimage:%BUILD_NUMBER% ./myproj2/htmlpage'
                bat 'docker push omarsa999/mysecondimage:%BUILD_NUMBER%'

                bat "docker tag omarsa999/mysecondimage:%BUILD_NUMBER% omarsa999/mysecondimage:latest"
                bat "docker push omarsa999/mysecondimage:latest"
            }
        }

        stage('Deploy K8s cluster with ansible') {
            steps {
                bat 'ssh omar@192.168.1.123 "ansible-playbook -i ~/ansiblefolder/inventory.ini ~/ansiblefolder/apply-cluster.yml"'
                }
            }

    }
}
